// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_mDBCgTV9ouZVx5F4H9UEReuieYGbUIg',
    appId: '1:643833047421:web:6e8010be531a59ec01c414',
    messagingSenderId: '643833047421',
    projectId: 'flutterriddles',
    authDomain: 'flutterriddles.firebaseapp.com',
    storageBucket: 'flutterriddles.appspot.com',
    measurementId: 'G-4F57WBQQY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7sT8ikBAUa3ZAUrIA_p8HXRrf3aW0sQ',
    appId: '1:643833047421:android:9d3f50a9dba62ff001c414',
    messagingSenderId: '643833047421',
    projectId: 'flutterriddles',
    storageBucket: 'flutterriddles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoz57PMpC-Oz9BHBwJbG7qPvZeOCa-Fg',
    appId: '1:643833047421:ios:b27b7e92844abce701c414',
    messagingSenderId: '643833047421',
    projectId: 'flutterriddles',
    storageBucket: 'flutterriddles.appspot.com',
    iosClientId: '643833047421-k05a14tde5d3a43hmogb76uh400gnh3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoz57PMpC-Oz9BHBwJbG7qPvZeOCa-Fg',
    appId: '1:643833047421:ios:f8cebfa58742574901c414',
    messagingSenderId: '643833047421',
    projectId: 'flutterriddles',
    storageBucket: 'flutterriddles.appspot.com',
    iosClientId: '643833047421-et7e2i1b7bu5h8jplkf387vmkd2c4ja9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsQuiz.RunnerTests',
  );
}
